---
title: "Vignette"
author: "Crista Gregg"
date: "6/10/2021"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)
```

## Functions to access API's
```{r franchise function}
get_franchise <- function(team_id = NA, team_name = NA){
  #connect to API
  get_endpoint <- GET('https://records.nhl.com/site/api/franchise') %>%
    content("text", encoding = 'UTF-8') %>%
    fromJSON(flatten = T) 
  df1 <- get_endpoint$data
  
  #if else statement to get team by name or ID
  ifelse(is.na(team_id) & is.na(team_name), franchise <- df1, 
         ifelse(is.na(team_id) & is.na(team_name) == FALSE, franchise <- filter(df1, fullName == team_name),
                ifelse(is.na(team_id) == FALSE & is.na(team_name), franchise <- filter(df1, id == team_id), 
                       franchise <- filter(df1, id == team_id | fullName == team_name)                                                         ))                                                         )
  return(franchise)
}

get_franchise(3, team_name = 'Montreal Wanderers')
```

```{r franchise team totals function}

get_franchise_team_totals <- function(team_id = NA, team_name = NA){
  #connect to API
  get_endpoint <- GET('https://records.nhl.com/site/api/franchise-team-totals') %>%
    content("text", encoding = 'UTF-8') %>%
    fromJSON(flatten = T) 
   df1 <- get_endpoint$data
  
  #if else statement to get team by name or ID
  ifelse(is.na(team_id) & is.na(team_name), franchise_team_totals <- df1, 
         ifelse(is.na(team_id) & is.na(team_name) == FALSE, franchise_team_totals <- filter(df1, teamName == team_name),
                ifelse(is.na(team_id) == FALSE & is.na(team_name), franchise_team_totals <- filter(df1, teamId == team_id), 
                       franchise_team_totals <- filter(df1, teamId == team_id | teamName == team_name)                                                         ))                                                         )
  return(franchise_team_totals)
}

get_franchise_team_totals(2)
```

```{r records function}
#function to call from franchise season records, goalie records, or skater records.
get_franchise_records <- function(record_type , team_id = NA, team_name = NA){
  
  #stop running if incorrect type of record entered
  if (!record_type %in% c('season', 'goalie', 'skater')){
    stop("Please enter record type of 'season', 'goalie', or 'skater'")
  }
  
  #connect to API
  URL <- paste0('https://records.nhl.com/site/api/franchise-', record_type, '-records')
  endpoint <- GET(URL) %>%
    content("text", encoding = 'UTF-8') %>%
    fromJSON(flatten = T) 
   df1 <- endpoint$data
  
  #if else statement to get team by name or ID
  ifelse(is.na(team_id) & is.na(team_name), franchise_records <- df1, 
         ifelse(is.na(team_id) & is.na(team_name) == FALSE, franchise_records <- filter(df1, franchiseName == team_name),
                ifelse(is.na(team_id) == FALSE & is.na(team_name), franchise_records <- filter(df1, franchiseId == team_id), 
                       franchise_records <- filter(df1, franchiseId == team_id | franchiseName == team_name)                                                         ))                                                         )
  return(franchise_records)
}

get_franchise_records(record_type = 'skater', team_id = 2)
```

```{r franchise detail function}
get_franchise_detail <- function(team_id = NA){
  
  #connect to API drilling down if needed
  URL1 <- paste0('https://records.nhl.com/site/api/franchise-detail')
  URL2 <- paste0('https://records.nhl.com/site/api/franchise-detail?cayenneExp=mostRecentTeamId=', as.character(team_id))
  
  ifelse(is.na(team_id), URL <- URL1, URL <- URL2)

  endpoint <- GET(URL) %>%
    content("text", encoding = 'UTF-8') %>%
    fromJSON(flatten = T) 
  
  return(endpoint$data)
}

get_franchise_detail()
?lubridate
```

```{r get stats}
get_team_stats <- function(team_id = 'All', team_name = NA){

if (team_id == 'All'){
#teams info to show where individual team info is located
get_endpoint_all <- GET('https://statsapi.web.nhl.com/api/v1/teams/') %>%
    content("text", encoding = 'UTF-8') %>%
    fromJSON(flatten = T) 

#use URL pulled from get_endpoint_all to grab data from all teams and then combine
URL_combine <- paste0('https://statsapi.web.nhl.com/api/v1/teams/', as.character(get_endpoint_all$teams$id), '/stats')
#get all team info
team_stats_combined_single_season <- team_stats_combined_rankings <- vector("list", length(URL_combine))

  for (i in 1:length(URL_combine)){
    team_stat <- GET(URL_combine[i]) %>%
      content("text", encoding = 'UTF-8') %>%
      fromJSON(flatten = T) 
   team_stats_combined_single_season[[i]] <- team_stat$stats$splits[[1]]
   team_stats_combined_rankings[[i]] <- team_stat$stats$splits[[2]]
  }
team_stats_combined_single_season <- bind_rows(team_stats_combined_single_season)
team_stats_combined_rankings <- bind_rows(team_stats_combined_rankings)

final <- list(single_season = team_stats_combined_single_season, rankings = team_stats_combined_rankings)
if (is.na(team_name)) return(final)
  else return(list(single_season = filter(team_stats_combined_single_season, team.name == team_name), rankings = filter(team_stats_combined_rankings, team.name == team_name)))

} else {
#if specific team wanted
  URL <- paste0('https://statsapi.web.nhl.com/api/v1/teams/', as.character(team_id), '/stats')
  get_endpoint <- GET(URL) %>%
      content("text", encoding = 'UTF-8') %>%
      fromJSON(flatten = T) 
  single_season <- get_endpoint$stats$splits[[1]] %>% 
    select(team.id, team.name, everything())
  rankings <- get_endpoint$stats$splits[[2]] %>% 
    select(team.id, team.name, everything())
  
  final <- list(single_season = single_season, rankings = rankings)
  return(final)
}
}

get_team_stats()
get_team_stats(team_id = 1)
get_team_stats(team_name = 'New York Islanders')
```

All functions have team_id and team_name as arguments to obtain desired record. 
```{r wrapper}
get_endpoint <- function(endpoint = c('franchise', 'team totals', 'records', 'details', 'stats'), ...){
  ifelse(endpoint == 'franchise', return(get_franchise(...)),
      ifelse(endpoint == 'team totals', return(get_franchise_team_totals(...)),
           ifelse(endpoint == 'records', return(get_franchise_records(...)),
                  ifelse(endpoint == 'details', return(get_franchise_detail(...)),
                         ifelse(endpoint == 'stats', return(get_team_stats(...)))))))
}

get_endpoint('team totals')
```


# Exploratory Data Analysis
Now I can easily pull data from several of the API endpoints. I will now perform an Exploratory Data Analysis. 

## Bar Plot exploring Team Wins
```{r}
team_totals <- get_endpoint('team totals')

team_wins <- team_totals %>%
  group_by(teamName) %>%
  summarize_at(c('wins', 'homeWins', 'roadWins'), sum, na.rm = T) %>% #add up rows by team
  arrange(desc(wins)) %>% #sort by number of wins
  head(25) %>% #only keep top 25
  ggplot(aes(reorder(teamName, wins)))
team_wins + geom_col(aes(y = wins, fill = 'darkred')) + #fill show go in aes layer so legend shows up 
  geom_col(aes(y = homeWins, fill = 'darkblue')) + #add layer to show proportion of wins that are home
  coord_flip() + 
  theme_minimal() +
  theme(legend.position = c(0.9,0.2)) +
  labs(x = 'Team Name', y = 'Total Wins', title = 'The 25 Teams with Greatest Number of Wins') +
  scale_fill_manual(name = 'Win Type', labels = c('Home', 'Away'), values = c('darkblue','darkred'))

```
# Scatter Plot with Text Labels
```{r}
season_records <- get_endpoint('records', record_type = 'season') %>%
  rename(team.id = id)
stats <- get_endpoint('stats')[[1]] #extract first element of this list

#combine records and stats
records_stats <- left_join(season_records, stats, by = 'team.id') %>%
  select(team.id, franchiseName, everything(), -team.name)
#str(records_stats)

#create scatter plot
ggplot(records_stats, aes(fewestGoals, stat.powerPlayPercentage)) +
  geom_text(aes(label = team.id), na.rm = T) +
  labs(x = 'Fewest Goals', y = 'Power Play Percentage', title = 'Record for Fewest Goals by Power Play Percentage for Each Team ID') +
  theme_minimal()

```

## Box plot for Number of Road Loss Streaks by Starting Month
```{r}
season_records %>% 
  select(starts_with('roadLoss')) %>% #select relevant data
  separate(roadLossStreakDates, into = 'start_month', sep = 3) %>% #separate column so I just have start month
  filter(is.na(start_month) == F) %>%
  mutate(month_numeric = ifelse(start_month == 'Jan', 13, 
                                ifelse(start_month == 'Feb', 14, match(start_month, month.abb)))) %>% #put Jan and Feb on the end so we are looking at the correct ordering of one season
  ggplot(aes(reorder(start_month, month_numeric), roadLossStreak)) +
    geom_boxplot() +
  labs(x = 'Start Month', y = 'Road Loss Streak', title = 'Road Loss Streaks by Start Month')

```

